dist: trusty
os: linux

language: node_js
node_js:
  - '12'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g @angular/cli
  - npm install -g firebase-tools

install:
  - npm install

deploy:
  provider: firebase
  # ⋮
  project: admin
